# Site settings
title: stmu.co 
email: stijn@stmu.co
description: > # Writer Theme is a responsive template
 focussed on typography, minimal design and
  quality photography built using the Jekyll platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title.html
nav_list:
  Home : ['Home', '/', 'fa-home']
  #Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  #Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/stijn', 'fa-user']
single_footer: '<p>&copy; 2016 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
gems:
    - jekyll-gist


# Build settings
# markdown: kramdown
